development:
    adapter: postgresql
    encoding: unicode
    database: wallboard_development
    pool: 5
    host: localhost
    port: 5432
    username: wallboard
    password: escal

test:
  adapter: postgresql
  encoding: unicode
  database: wallboard_test
  pool: 5
  username: wallboard
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: wallboard_production
  pool: 5
  host: localhost
  port: 5432
  username: wallboard
  password: wallboard
